# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YFCfYO60d4sK_BKJStQLBjzfvXbYSXEr
"""



#### Python group of programs to convert temperature values between Celsius and Fahrenheit
#### Author: Syed Waqar Ali
#### version: 1.0


# function to convert celsius to fahrenheit
def celsius_to_fahrenheit(celsius):
  fahrenheit = (celsius * 9/5) + 32
  return fahrenheit

# function to convert fahrenheit to celsius
def fahrenheit_to_celsius(fahrenheit):
  celsius = (fahrenheit - 32) * 5/9
  return celsius

# function to call relevant function based on selected units
def convert_temperature(value, from_unit, to_unit):
  if from_unit == "C" and to_unit == "F":
    return celsius_to_fahrenheit(value)
  elif from_unit == "F" and to_unit == "C":
    return fahrenheit_to_celsius(value)
  else:
    raise ValueError("Invalid temperature unit")

# function to show the error message when invalid input values are provided
def execute_invalid_input():
  print('\n\nInvalid input!\n')
  print('Starting again!\n\n')
  execute_start()

# function start execution of the main function that collects input values from user
def execute_start():
  user_value = input("Enter numeric temperature value to convert:")

  if( not user_value.isnumeric() ):
    execute_invalid_input()

  user_value_unit = str(input("Enter this temperature value's unit (C or F):"))

  if( (user_value_unit.upper() == 'C') or (user_value_unit.upper() == 'F') ):
    from_unit = user_value_unit.upper()
    if(from_unit == 'C'):
      to_unit = 'F'
    else:
      to_unit = 'C'

    converted_value = convert_temperature(int(user_value), from_unit, to_unit)
    print(f"{user_value} degrees {from_unit} is equal to {round(converted_value,2)} degrees {to_unit}.\n\n")
  else:
    execute_invalid_input()

# initialize the main execution function
execute_start()